package uk.gov.justice.digital.hmpps.calculatereleasedatesapi.integration

import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean
import org.springframework.boot.info.BuildProperties
import org.springframework.boot.test.context.TestConfiguration
import org.springframework.context.annotation.Bean
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Properties

@TestConfiguration
class TestBuildPropertiesConfiguration {

  companion object {
    private val properties = Properties().apply {
      setProperty("artifact", "calculate-release-dates-api")
      setProperty("by", "foo.bar")
      setProperty("group", "uk.gov.justice.digital.hmpps")
      setProperty("machine", "MJ000000")
      setProperty("name", "calculate-release-dates-api")
      setProperty("operatingSystem", "Mac OS X (14.3.1)")
      setProperty("time", LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME))
      setProperty("version", LocalDate.now().format(DateTimeFormatter.ISO_DATE))
    }
    val TEST_BUILD_PROPERTIES = BuildProperties(properties)
  }

  /**
   * Normally generated by gradle using springboot's build info goal but it's not compatible with build and run using intellij which this fixes.
   * The proper version from Gradle is used during CI. See META-INF/build-info.properties for properties.
   */
  @Bean
  @ConditionalOnMissingBean(BuildProperties::class)
  fun buildProperties(): BuildProperties = TEST_BUILD_PROPERTIES
}
