version: "3"
services:
  calculate-release-dates-db:
    image: postgres
    networks:
      - hmpps
    container_name: calculate-release-dates-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=calculate-release-dates
      - POSTGRES_USER=calculate-release-dates
      - POSTGRES_DB=calculate_release_dates

  calculate-release-dates-api:
    build:
      context: .
    network_mode: "host"
    container_name: calculate-release-dates-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
