
hdced:
  maximum-sentence-length-years: 4
  minimum-custodial-period-days: 42
  custodial-period-mid-point-days: 360
  custodial-period-below-midpoint-minimum-deduction-days: 28
  custodial-period-above-midpoint-deduction-days: 179
  minimum-days-on-hdc: 14

hdced4:
  envelope-minimum:
    value: 12
    unit: WEEKS
  envelope-mid-point:
    value: 720
    unit: DAYS
  minimum-custodial-period-days: 14
  deduction-days: 179
  hdc4-commencement-date: 2024-06-17

ersed:
  max-period-days: 544
release-point-multipliers:
  multipliers:
    - tracks:
        - EDS_AUTOMATIC_RELEASE
        - SDS_TWO_THIRDS_RELEASE
        - SDS_PLUS_RELEASE
      multiplier: 0.66666
    - tracks:
        - EDS_DISCRETIONARY_RELEASE,
        - SOPC_PED_AT_TWO_THIRDS,
        - SOPC_PED_AT_HALFWAY,
        - AFINE_ARD_AT_FULL_TERM,
        - BOTUS
        - BOTUS_WITH_HISTORIC_TUSED
      multiplier: 1.0
  default: 0.5

sds-early-release-tranches:
  tranche-one-date: 2024-07-29
  tranche-two-date: 2099-01-01
