sds-40-early-release-tranches:
  tranche-one-date: 2024-09-10
  tranche-two-date: 2024-10-22
  tranche-three-date: 2024-12-16

release-point-multipliers:
  earlyReleasePoint: 0.4

early-release-configuration:
  configurations:
    - release-multiplier: ${release-point-multipliers.earlyReleasePoint}
      filter: SDS_40_EXCLUSIONS
      tranches:
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 5
          date: ${sds-40-early-release-tranches.tranche-one-date}
          name: TRANCHE_1
        - type: FINAL
          date: ${sds-40-early-release-tranches.tranche-two-date}
          name: TRANCHE_2
        - type: SDS_40_TRANCHE3
          date: ${sds-40-early-release-tranches.tranche-three-date}
    - release-multiplier: 0.33
      filter: SDS_40_EXCLUSIONS
      tranches:
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 2
          date: 2025-09-01
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 3
          date: 2025-10-01
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 4
          date: 2025-11-01
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 5
          date: 2025-12-01
        - type: FINAL
          date: 2026-01-01
        