sds-40-early-release-tranches:
  tranche-one-date: 2024-09-10
  tranche-two-date: 2024-10-22
  tranche-three-date: 2024-12-16

release-point-multipliers:
  earlyReleasePoint: FORTY_PERCENT

sds-legislations:
  progression-model-legislation:
    release-multiplier:
      SDS: ONE_THIRD
      SDS_PLUS: ONE_HALF
    filter: SDS_OR_SDS_PLUS_ADULT
    tranches:
      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 729
        date: 2026-09-02
        name: TRANCHE_1

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 1094
        date: 2026-10-13
        name: TRANCHE_2

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 1460
        date: 2026-11-10
        name: TRANCHE_3

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 1825
        date: 2026-12-08
        name: TRANCHE_4

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 2190
        date: 2027-01-12
        name: TRANCHE_5

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 2921
        date: 2027-02-09
        name: TRANCHE_6

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 3651
        date: 2027-03-09
        name: TRANCHE_7

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 4747
        date: 2027-04-13
        name: TRANCHE_8

      - type: SENTENCE_LENGTH
        unit: DAYS
        duration: 6208
        date: 2027-05-11
        name: TRANCHE_9

      - type: FINAL
        date: 2027-06-08
        name: TRANCHE_10
  sds40-youth-repeal:
    commencement-date: 2026-09-01
    release-multiplier:
      SDS: ONE_HALF
      SDS_PLUS: TWO_THIRDS
    filter: YOUTH
