release-point-multipliers:
  multipliers:
    - tracks:
        - EDS_AUTOMATIC_RELEASE
        - SDS_TWO_THIRDS_RELEASE
        - SDS_PLUS_RELEASE
      multiplier: 0.66666
    - tracks:
        - EDS_DISCRETIONARY_RELEASE,
        - SOPC_PED_AT_TWO_THIRDS,
        - SOPC_PED_AT_HALFWAY,
        - AFINE_ARD_AT_FULL_TERM,
        - BOTUS
      multiplier: 1.0
    - tracks:
        - SDS_EARLY_RELEASE
      multiplier: 0.45
  default: 0.5
hdced4:
  hdc4-commencement-date: 2024-06-10