
hdced:
  minimum-custodial-period-days: 42
  custodial-period-mid-point-days-pre-hdc-365: 360
  custodial-period-below-midpoint-minimum-deduction-days: 28
  custodial-period-above-midpoint-deduction-days-pre-hdc-365: 179
  minimum-days-on-hdc: 14
  custodial-period-mid-point-days-post-hdc-365: 730
  custodial-period-above-midpoint-deduction-days-post-hdc-365: 364

ersed:
  ers-50-max-period-amount: 544
  ers-50-max-period-unit: DAYS
  ers-50-release-point: 0.5
  ers-30-max-period-amount: 4
  ers-30-max-period-unit: YEARS
  ers-30-release-point: 0.3

sds-40-early-release-tranches:
  tranche-one-date: 2024-09-10
  tranche-two-date: 2024-10-22
  tranche-three-date: 2024-12-16

release-point-multipliers:
  earlyReleasePoint: 0.4

early-release-configuration:
  configurations:
    - release-multiplier:
        SDS:
          numerator: ${release-point-multipliers.earlyReleasePoint}
      filter: SDS_40_EXCLUSIONS
      tranches:
        - type: SENTENCE_LENGTH
          unit: YEARS
          duration: 5
          date: ${sds-40-early-release-tranches.tranche-one-date}
          name: TRANCHE_1
        - type: FINAL
          date: ${sds-40-early-release-tranches.tranche-two-date}
          name: TRANCHE_2
        - type: SDS_40_TRANCHE3
          date: ${sds-40-early-release-tranches.tranche-three-date}
        