  {{- if .Values.deleteOldPreliminaryCalculationsCronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-service.fullname" . | trunc 27 }}-delete-old-prelim-calcs
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}

spec:
  schedule: "{{ .Values.deleteOldPreliminaryCalculationsCronJob.schedule }}"
  timeZone: "{{ .Values.deleteOldPreliminaryCalculationsCronJob.timeZone }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0 # Ensure the job controller does not retry if the pod fails
      template:
        spec:
          restartPolicy: Never # Ensure the kubelet does not restart the container on failure
          containers:
            - name: delete-old-prelim-calcs-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools:latest
              imagePullPolicy: IfNotPresent
              command: [ "/bin/sh", "-c" ]
              args:
                - curl -XPOST --connect-timeout 5 --max-time 10 http://{{ include "generic-service.fullname" . }}/scheduled-task/delete-old-preliminary-calculations
              securityContext:
                {{- toYaml .Values.deleteOldPreliminaryCalculationsCronJob.securityContext | nindent 16 }}
  {{- end }}