package uk.gov.justice.digital.hmpps.calculatereleasedatesapi.enumerations

enum class AdjustmentType {
  REMAND,
  TAGGED_BAIL,
  UNLAWFULLY_AT_LARGE,
  ADDITIONAL_DAYS_AWARDED,
  RESTORATION_OF_ADDITIONAL_DAYS_AWARDED,
  ADDITIONAL_DAYS_SERVED,
  RECALL_REMAND,
  RECALL_TAGGED_BAIL,
  RELEASE_UNUSED_ADA,
  LICENSE_UNUSED_ADA
}
