package uk.gov.justice.digital.hmpps.calculatereleasedatesapi.enumerations

enum class CalculationRule {
  HDCED_GE_MIN_PERIOD_LT_MIDPOINT,
  HDCED_GE_MIDPOINT_LT_MAX_PERIOD,
  HDCED_MINIMUM_CUSTODIAL_PERIOD,
  CONSECUTIVE_SENTENCE_HDCED_MINIMUM_CUSTODIAL_PERIOD,
  CONSECUTIVE_SENTENCE_HDCED_MINIMUM_CUSTODIAL_PERIOD_LAST_SENTENCE_SDS,
  TUSED_LICENCE_PERIOD_LT_1Y,
  LED_CONSEC_ORA_AND_NON_ORA,
  UNUSED_ADA,
  IMMEDIATE_RELEASE,
  PED_EQUAL_TO_LATEST_NON_PED_CONDITIONAL_RELEASE,
  PED_EQUAL_TO_LATEST_NON_PED_ACTUAL_RELEASE,
  HDCED_ADJUSTED_TO_CONCURRENT_CONDITIONAL_RELEASE,
  HDCED_ADJUSTED_TO_CONCURRENT_ACTUAL_RELEASE,
  ERSED_TWO_THIRDS,
  ERSED_HALFWAY,
  ERSED_MAX_PERIOD,
  ERSED_MIXED_TERMS,
  ERSED_ADJUSTED_TO_CONCURRENT_TERM,
  ERSED_BEFORE_SENTENCE_DATE,
  ERSED_ADJUSTED_TO_MTD,
}
