package uk.gov.justice.digital.hmpps.calculatereleasedatesapi.model

data class SentenceCalculationDates(
  val mtdCalculatedDate: String,
  val mtdOverrideDate: String,
  val etdCalculatedDate: String,
  val etdOverrideDate: String,
  val ltdOverrideDate: String,
  val ltdCalculatedDate: String,
  val sentenceExpiryDate: String?,
  val automaticReleaseDate: String?,
  val conditionalReleaseDate: String?,
  val nonParoleDate: String?,
  val postRecallReleaseDate: String?,
  val licenceExpiryDate: String?,
  val homeDetentionCurfewEligibilityDate: String?,
  val paroleEligibilityDate: String?,
  val homeDetentionCurfewActualDate: String?,
  val actualParoleDate: String?,
  val releaseOnTemporaryLicenceDate: String?,
  val earlyRemovalSchemeEligibilityDate: String?,
  val earlyTermDate: String?,
  val midTermDate: String?,
  val lateTermDate: String?,
  val topupSupervisionExpiryDate: String?,
  val tariffDate: String?,
  val dtoPostRecallReleaseDate: String?,
  val tariffEarlyRemovalSchemeEligibilityDate: String?,
  val effectiveSentenceEndDate: String?,
  val bookingId: Long,
  val sentenceStartDate: String,
  val additionalDaysAwarded: Int?,
  val automaticReleaseOverrideDate: String?,
  val conditionalReleaseOverrideDate: String?,
  val nonParoleOverrideDate: String?,
  val postRecallReleaseOverrideDate: String?,
  val dtoPostRecallReleaseDateOverride: String?,
  val nonDtoReleaseDate: String?,
  val sentenceExpiryCalculatedDate: String?,
  val sentenceExpiryOverrideDate: String?,
  val licenceExpiryCalculatedDate: String?,
  val licenceExpiryOverrideDate: String?,
  val paroleEligibilityCalculatedDate: String?,
  val paroleEligibilityOverrideDate: String?,
  val topupSupervisionExpiryCalculatedDate: String?,
  val topupSupervisionExpiryOverrideDate: String?,
  val homeDetentionCurfewEligibilityCalculatedDate: String?,
  val homeDetentionCurfewEligibilityOverrideDate: String?,
  val nonDtoReleaseDateType: NonDtoReleaseType,
  val confirmedReleaseDate: String?,
  val releaseDate: String?,
  val topupSupervisionStartDate: String?,
  val homeDetentionCurfewEndDate: String?,
  val judiciallyImposedSentenceLength: String?,
  val comment: String?,
  val reasonCode: String?,)

enum class NonDtoReleaseType {
  ARD,
  CRD,
  NPD,
  PRRD
}
