generic-service:
  productId: "DPS014"
  nameOverride: calculate-release-dates-api

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/calculate-release-dates-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: calculate-release-dates-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_ENABLED: "true"
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    CONCURRENT_CONSECUTIVE_SENTENCES_ENABLED: "true"
    HISTORIC_SLED_ENABLED: "true"
    FTR_48_MANUAL_JOURNEY: "true"
    USE_ERS30_CALCULATION: "true"
    VALIDATE_POST_RECALL_REPEAL_DATE: "false"
    SUPPORT_INACTIVE_SENTENCES_AND_ADJUSTMENTS: "false"
    EXTERNAL_MOVEMENTS_SDS_40_FEATURE_TOGGLE: "true"
    EXTERNAL_MOVEMENTS_ADJUSTMENTS_FEATURE_TOGGLE: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    rds-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    digital-prison-reporting:
      DPR_USER: "DPR_USER"
      DPR_PASSWORD: "DPR_PASSWORD"
    calculate-release-dates-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    calculate-release-dates-api-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
  allowlist:
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    groups:
      - internal

  retryDlqCronjob:
    enabled: true

generic-prometheus-alerts:
  targetApplication: calculate-release-dates-api

generic-data-analytics-extractor:
  enabled: true
  databaseSecretName: rds-instance-output
  destinationS3SecretName: analytical-platform-reporting-s3-bucket
  serviceAccountName: calculate-release-dates-to-ap-s3
  args: "extract_table_names.py && extract_psql_all_tables_to_csv.sh && transfer_local_to_s3.sh"
  resources:
    requests:
      memory: 2G
      cpu: 1
    limits:
      memory: 4G