---
# Per environment values which override defaults in calculate-release-dates-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: calculate-release-dates-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    EDS_FEATURE_TOGGLE: false
    PCSC_START_DATE: 2022-06-27

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
