---
# Per environment values which override defaults in calculate-release-dates-api/values.yaml

generic-service:

  ingress:
    host: calculate-release-dates-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "alt-3-calculation-params"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api.prison.service.justice.gov.uk
    ADJUSTMENTS_API_URL: https://adjustments-api.hmpps.service.justice.gov.uk
    MANAGE-OFFENCES_API_URL: https://manage-offences-api.hmpps.service.justice.gov.uk
    BOTUS_FEATURE_TOGGLE: "false"
    SDS_EARLY_RELEASE_FEATURE_TOGGLE: "true"
    SDS_EARLY_RELEASE_UNSUPPORTED_FEATURE_TOGGLE: "false"
    SDS_EARLY_RELEASE_HINTS_FEATURE_TOGGLE: "true"

  serviceAccountName: calculate-release-dates-api-prod

  resources:
    requests:
      memory: 2G
    limits:
      memory: 4G

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
