---
# Per environment values which override defaults in calculate-release-dates-api/values.yaml

generic-service:

  ingress:
    host: calculate-release-dates-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://api.prison.service.justice.gov.uk
    ADJUSTMENTS_API_URL: https://adjustments-api.hmpps.service.justice.gov.uk
    MANAGE-OFFENCES_API_URL: https://manage-offences-api.hmpps.service.justice.gov.uk
    BOTUS_FEATURE_TOGGLE: "false"

  serviceAccountName: calculate-release-dates-api-prod

  resources:
  requests:
    memory: 2G
  limits:
    memory: 4G

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
