---
# Per environment values which override defaults in calculate-release-dates-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: calculate-release-dates-api-alt-dev.hmpps.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine DetectionOnly
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

  env:
    SPRING_PROFILES_ACTIVE: "calculation-params"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    ADJUSTMENTS_API_URL: https://adjustments-api-dev.hmpps.service.justice.gov.uk
    MANAGE-OFFENCES_API_URL: https://manage-offences-api-dev.hmpps.service.justice.gov.uk
    BOTUS_FEATURE_TOGGLE: "true"
    SDS_EARLY_RELEASE_FEATURE_TOGGLE: "true"
    SDS_EARLY_RELEASE_HINTS_FEATURE_TOGGLE: "true"
    SUPPORT_INACTIVE_SENTENCES_AND_ADJUSTMENTS: "true"
    TORERA_OFFENCE_TO_MANUAL_JOURNEY: "false"
  # Switches off the allow list in the DEV env only.
  allowlist: null

  serviceAccountName: calculate-release-dates-api-dev

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  targetApplication: calculate-release-dates-api-alt-dev
  businessHoursOnly: true
  alertSeverity: legacy-replacement-alerts-non-prod

generic-data-analytics-extractor:
  enabled: false
  cronJobNameOverride: calculate-release-dates-alt