---
# Per environment values which override defaults in calculate-release-dates-api/values.yaml

generic-service:

  ingress:
    host: calculate-release-dates-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "calculation-params"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PRISON_API_URL: https://prison-api.prison.service.justice.gov.uk
    ADJUSTMENTS_API_URL: https://adjustments-api.hmpps.service.justice.gov.uk
    MANAGE-OFFENCES_API_URL: https://manage-offences-api.hmpps.service.justice.gov.uk
    NOMIS-SYNC-MAPPING_API_URL: https://nomis-sync-prisoner-mapping.hmpps.service.justice.gov.uk
    HISTORIC_SLED_ENABLED: "false"

  serviceAccountName: calculate-release-dates-api-prod

  resources:
    requests:
      memory: 2G
    limits:
      memory: 4G

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

  namespace_secrets:
    sqs-bulk-comparison-queue:
      HMPPS_SQS_QUEUES_BULKCOMPARISON_QUEUE_NAME: "sqs_name"
    sqs-bulk-comparison-dlq:
      HMPPS_SQS_QUEUES_BULKCOMPARISON_DLQ_NAME: "sqs_name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  sqsAlertsQueueNames:
    - "calculate-release-dates-team-prod-bulk_comparison_queue"
    - "calculate-release-dates-team-prod-bulk_comparison_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  alertSeverity: legacy-replacement-alerts
