CREATE TABLE calculation_request_manual_reason
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_request_id BIGINT,
    code                   VARCHAR(255),
    message                VARCHAR(255),
    CONSTRAINT pk_calculationrequestmanualreason PRIMARY KEY (id)
);

ALTER TABLE calculation_request_manual_reason
    ADD CONSTRAINT uc_calculationrequestmanualreason_calculationrequestid UNIQUE (id, calculation_request_id);

ALTER TABLE calculation_request_manual_reason
    ADD CONSTRAINT FK_CALCULATIONREQUESTMANUALREASON_ON_CALCULATIONREQUESTID FOREIGN KEY (calculation_request_id) REFERENCES calculation_request (id);