COMMENT ON TABLE Approved_Dates IS E'Description: For user input release dates, the user will need to approve the date on the UI. This table holds these input dates and the calculation type. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Approved_Dates_Submission IS E'Description: Holds metadata information for user inputted release date submissions. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Approved_Dates_Submission_Approved_Dates IS E'Description: Links the Approved Dates table to the Approved Dates Submission table. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Bank_Holiday_Cache IS E'Description: This is an internal table which holds bank holiday dates. This is used as reference data, if the release date falls on a bank holiday then the prisoner can be eligible for release the previous day. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Calculation_Outcome IS E'Description: Holds the output from the release date calculation. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Calculation_Reason IS E'Description: Holds the reason why the release date calculation was generated. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Calculation_Request IS E'Description: Holds all the inputs involved in the release date calculation. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Calculation_Request_Sentence_User_Input IS E'Description: Legacy table, originally per sentence the user would be asked whether the sentences are SDS+ sentences.  \nDomain: Person sentence calculations ';
COMMENT ON TABLE Calculation_Request_User_Input IS E'Description: For the user to input whether ERSED (Early Removal Scheme Eligibility Date) is calculated. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison IS E'Description: Holds data on comparisons run in the system. Comparisons are run on release dates that have already been stored and recalculations of the release dates. The system allows for bulk comparisons to be run. Comparisons are used for validation testing and testing new sentence types or calculation logic in the system. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Person IS E'Description: Holds data on each individual used in a comparison. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Person_Discrepancy IS E'Description: Holds the details of the comparison discrepancy. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Person_Discrepancy_Cause IS E'Description: Holds the cause of the comparison discrepancy. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Person_Discrepancy_Impact IS E'Description: Holds the impact reference data of the comparison discrepancy. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Person_Discrepancy_Priority IS E'Description: Holds the priority reference data of the comparison discrepancy. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Comparison_Status IS E'Description: Holds the status of the comparison run. \nDomain: Person sentence calculations ';
COMMENT ON TABLE Genuine_Override IS E'Description: Holds all the override requests for release dates.  \nDomain: Person sentence calculations ';
COMMENT ON TABLE Tranche_Outcome IS E'Description: Holds all calculation requests, indicates which calculation request allows for early release at specific intervals as part of the sds40 early release scheme. \nData Quality Issues: The tranche allocation is stored at the time of the calculation, policy may change their understanding after. Thus, the tranche allocation may become out of date.\n   Data Quality Parameter: Accuracy\n   Source of Data Quality Issue: CRDS \nDomain: Person sentence calculations ';

COMMENT ON COLUMN Approved_Dates.calculation_date_type IS E'Description: The type of release date entered by the user. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates.outcome_date IS E'Description: The release date which has been input by the user on the UI. This is a non-calculated date. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates.id IS E'Description: The id of the approved dates record. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission.submitted_by_username IS E'Description: The user that input the release date. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission.prisoner_id IS E'Description: The id of the prisoner which the release date refers to. \nSource System: NOMIS ';
COMMENT ON COLUMN Approved_Dates_Submission.id IS E'Description: The id of the approved date submission record. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission.booking_id IS E'Description: The id of the booking related to the prisoner. \nSource System: NOMIS ';
COMMENT ON COLUMN Approved_Dates_Submission.calculation_request_id IS E'Description: The id of the calculation request record. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission.submitted_at IS E'Description: The timestamp of when the user input release date was submitted. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission_Approved_Dates.approved_dates_id IS E'Description: The id of the approved dates record. \nSource System: CRDS ';
COMMENT ON COLUMN Approved_Dates_Submission_Approved_Dates.approved_dates_submission_id IS E'Description: The id of the approved dates submission record. \nSource System: CRDS ';
COMMENT ON COLUMN Bank_Holiday_Cache.cached_at IS E'Description: The timestamp of when the bank holiday record was cached. \nSource System: CRDS ';
COMMENT ON COLUMN Bank_Holiday_Cache.id IS E'Description: The id of the bank holiday cache record. \nSource System: CRDS ';
COMMENT ON COLUMN Bank_Holiday_Cache.data IS E'Description: Holds bank holiday dates. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Outcome.calculation_date_type IS E'Description: The type of the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Outcome.id IS E'Description: The id of the calculation outcome record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Outcome.outcome_date IS E'Description: The release date outcome from the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Outcome.calculation_request_id IS E'Description: The id of the calculation request record. This can be repeated multiple times in this table, as each calculation request can calculate multiple outcome dates due to having multiple calculation types. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.is_other IS E'Description: Whether or not the reason is something other than the options given to the user in the UI. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.nomis_comment IS E'Description: The NOMIS reason why the calculation was generated, this gets sent to NOMIS. This is used for the bidirectional sync between NOMIS and CRDS. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.display_name IS E'Description: The reason why the calculation was generated. This gets selected by the user. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.id IS E'Description: The id of the calculation reason record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.nomis_reason IS E'Description: The NOMIS reason code, this gets sent to NOMIS. This is used for the bidirectional sync between NOMIS and CRDS. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.display_rank IS E'Description: The order for the calculation reasons to be shown on the UI. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.is_bulk IS E'Description: Whether or not the calculation request has been done in bulk. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Reason.is_active IS E'Description: Whether or not the calculation reason is still used and active. If a calculation reason is not being used regularly, then this calculation reason will become inactive. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.reason_for_calculation IS E'Description: Holds the id for the reason for calculation record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.id IS E'Description: The id related to the calculation request record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.return_to_custody_date IS E'Description: The date the prisoner was arrested. If the prisoner was already in custody at the time of the recall then this will be the same as the revocation_date. This will be the date at the point of time the calculation was done. This is used as an input into the calculation. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.other_reason_for_calculation IS E'Description: The reason for calculation input by the user, if the reason is not in the list shown on the UI. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.booking_id IS E'Description: The booking id related to the calculation request. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.sentence_and_offences IS E'Description: All relevant sentence and offence data which is used as inputs in the release date calculation. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.calculated_at IS E'Description: The timestamp of when the calculation was generated. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.prisoner_id IS E'Description: The id related to the prisoner. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.adjustments_version IS E'Description: The adjustments data can get updated, this is to show which version of the code the adjustments data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.calculated_by_username IS E'Description: The user which generated the calculation in the system. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.calculation_status IS E'Description: The status of the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.adjustments IS E'Description: Any adjustments data to add as inputs into the calculation. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.prisoner_location IS E'Description: The prison where the prisoner is located at the time of calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.input_data IS E'Description: All input data used in the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.breakdown_html IS E'Description: When a calculation is generated, the UI will produce a breakdown of how the output was calculated. This field saves the breakdown as it was shown to the user on the UI at the point of time of calculation. This is used as a safeguarding measure. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.version IS E'Description: The calculation request data can get updated, this is to show which version of the code the calculation request data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.offender_fine_payments_version IS E'Description: The fine payments data can get updated, this is to show which version of the code the fine payments data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.historical_tused_source IS E'Description: TUSED is the Post Sentence Supervision Expiry Date. This field is the source system of where the TUSED date was calculated. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.calculation_type IS E'Description: The type of the calculation.  \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.sentence_and_offences_version IS E'Description: The sentences and offences data can get updated, this is to show which version of the code the sentences and offences data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.prisoner_details_version IS E'Description: The prisoner details data can get updated, this is to show which version of the code the prisoner details data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.offender_fine_payments IS E'Description: The fine amount the offender has been sentenced to pay. This is used as an input in the calculation. \nSource System: NOMIS ';
COMMENT ON COLUMN Calculation_Request.calculation_reference IS E'Description: The reference id for the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.prisoner_details IS E'Description: Details on the prisoner. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request.return_to_custody_date_version IS E'Description: The return to custody data can get updated, this is to show which version of the code the return to custody data is being applied with to the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.sentence_sequence IS E'Description: The sentence being referred to by the user, when an offender is serving a sequence of sentences.  \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.type IS E'Description: The type of the calculation request. Legacy field. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.calculation_request_user_input_id IS E'Description: The id of the calculation request user input record. This is used to link to the Calculation Request User Input table. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.offence_code IS E'Description: The offence code related to the sentence. \nSource System: Manage Offences System ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.user_choice IS E'Description: Whether or not the offence is SDS+. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.nomis_matches IS E'Description: Whether or not the NOMIS release date matches the user input release date.  \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_Sentence_User_Input.id IS E'Description: The id of the calculation request sentence user input record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_User_Input.calculate_ersed IS E'Description: Whether or not the offender can get an early release and deportation. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_User_Input.id IS E'Description: The id of the calculation request user input record. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_User_Input.use_offence_indicators IS E'Description: Legacy field. Whether to use offence indicators from NOMIS  for the calculation input. \nSource System: CRDS ';
COMMENT ON COLUMN Calculation_Request_User_Input.calculation_request_id IS E'Description: The id of the calculation request. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.calculated_at IS E'Description: The timestamp of when the comparison took place. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.number_of_people_compared IS E'Description: The number of prisoners used in the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.number_of_people_comparison_failed_for IS E'Description: The number of prisoners used in the comparison, where there is a mismatch. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.comparison_reference IS E'Description: The reference code of the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.comparison_type IS E'Description: The type of comparison.  \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.id IS E'Description: The id of the comparison record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.criteria IS E'Description: The id of the prisoners which are run in the comparison. This is populated when the comparison_type is MANUAL. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.comparison_status_id IS E'Description: The id of the comparison status. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.comparison_short_reference IS E'Description: Shortened reference code of the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.prison IS E'Description: The prison location of the prisoners run in the comparison. This is populated when the comparison_type is ESTABLISHMENT_FULL. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison.calculated_by_username IS E'Description: The user that generated the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.validation_messages IS E'Description: When a comparison is run, the system will check sentence and offence data for each prisoner. If this information is not supported or there is missing information then the reason why the validation failed will be populated in this message. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.short_reference IS E'Description: Shortened reference code for the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.override_dates IS E'Description: This captures any release dates which have been overridden. \nSource System: NOMIS ';
COMMENT ON COLUMN Comparison_Person.person IS E'Description: The id of the prisoner used in the comparison. \nSource System: NOMIS ';
COMMENT ON COLUMN Comparison_Person.id IS E'Description: The id of the comparison person record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.fatal_exception IS E'Description: The error message when the comparison fails to run. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.latest_booking_id IS E'Description: The most recent booking id related to the prisoner in the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.is_fatal IS E'Description: Whether or not the comparison failed to run due to an error. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.is_active_sex_offender IS E'Description: Whether or not the prisoner is an active sex offender. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.is_valid IS E'Description: When a comparison is run, the system will check sentence and offence data for each prisoner. If this information is not supported or there is missing information then is_valid will be FALSE. If there are no validation issues then is_valid will be TRUE. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.reference IS E'Description: The reference code for the comparison person record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.hdced_four_plus_date IS E'Description: The hdced four plus date stored after calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.is_match IS E'Description: Whether or not the prisoners release dates match in the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.establishment IS E'Description: The prison id of where the prisoner is located. This will be populated when the comparison_type is MANUAL. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.calculation_request_id IS E'Description: The id of the calculation request record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.breakdown_by_release_date_type IS E'Description: Information on the release date calculation including any rules affecting the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.comparison_id IS E'Description: The id of the comparison run. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.sds_plus_sentences_identified IS E'Description: Stores sentences that are SDS+ for the prisoner. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.calculated_at IS E'Description: Timestamp of when the release date was calculated. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.nomis_dates IS E'Description: The release dates from NOMIS. \nSource System: NOMIS ';
COMMENT ON COLUMN Comparison_Person.mismatch_type IS E'Description: The reason for mismatches when the comparison has been run. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.calculated_by_username IS E'Description: The user who generated the release date calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person.last_name IS E'Description: The last name of the prisoner. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.id IS E'Description: The id of the comparison person discrepancy record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.priority_id IS E'Description: The discrepancy priority id. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.superseded_by_id IS E'Description: The id of the discrepancy record which is replacing a historic discrepancy record. This is used for auditing purposes. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.created_by IS E'Description: The user that generated the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.impact_id IS E'Description: The discrepancy impact id. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.created_at IS E'Description: The timestamp of when the comparison was generated. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.action IS E'Description: The action to be done following the discrepancy. Input by the user. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.detail IS E'Description: Additional detail on the discrepancy, input by the user. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy.comparison_person_id IS E'Description: The id of the prisoner referred to in the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Cause.detail IS E'Description: Additional detail of the cause of the discrepancy. Input by the user. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Cause.discrepancy_id IS E'Description: The id of the comparison discrepancy. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Cause.category IS E'Description: The category of the discrepancy cause. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Cause.id IS E'Description: The id of the discrepancy cause record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Cause.sub_category IS E'Description: The sub category of the discrepancy cause. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Impact.id IS E'Description: The id of the discrepancy impact record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Impact.impact IS E'Description: The impact of the discrepancy. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Priority.priority IS E'Description: The priority of the discrepancy. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Person_Discrepancy_Priority.id IS E'Description: The id of the discrepancy priority record. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Status.name IS E'Description: The status of the comparison. \nSource System: CRDS ';
COMMENT ON COLUMN Comparison_Status.id IS E'Description: The id of the comparison status record. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.saved_at IS E'Description: The timestamp of when the override was saved. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.original_calculation_request_id IS E'Description: The id of the initial calculation request record. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.saved_calculation_id IS E'Description: The id of the updated calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.id IS E'Description: The id of the genuine override record. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.reason IS E'Description: The reason for overriding or not overriding the release date. \nSource System: CRDS ';
COMMENT ON COLUMN Genuine_Override.is_overridden IS E'Description: Whether the override request results in a saved calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.calculation_request_id IS E'Description: The id of the calculation request record. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.allocated_tranche IS E'Description: Legacy field. The allocated tranche. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.affected_by_sds40 IS E'Description: Whether or not a release date is affected by the Standard Determinate Sentences 40% scheme. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.outcome_date IS E'Description: The release date output from the calculation. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.id IS E'Description: The id of the tranche outcome record. \nSource System: CRDS ';
COMMENT ON COLUMN Tranche_Outcome.tranche IS E'Description: The allocated tranche from Policy\'s understanding at the time the calculation was performed. \nSource System: CRDS ';
