CREATE TABLE calculation_outcome_historic_override
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_request_id            bigint                                  not null references calculation_request (id),
    calculation_outcome_id            bigint                                  not null references calculation_outcome (id),
    calculation_outcome_date          date                                    not null,
    historic_calculation_outcome_id   bigint                                  not null references calculation_outcome (id),
    historic_calculation_outcome_date date                                    not null,
    CONSTRAINT pk_dominant_historic_calculation_outcome PRIMARY KEY (id)
);