CREATE TABLE dominant_historic_calculation_outcome
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_outcome_id bigint                                  not null references calculation_outcome (id),
    outcome_date           date                                    not null,
    booking_id             bigint,
    CONSTRAINT pk_dominant_historic_calculation_outcome PRIMARY KEY (id)
)