CREATE TABLE calculation_request_sentence
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_request_id            BIGINT NOT NULL REFERENCES calculation_request (id),
    input_sentence_data_json          JSONB NOT NULL,
    sentence_adjustments_json         JSONB NOT NULL,
    impacts_final_release_date        BOOLEAN NOT NULL,
    release_multiplier                NUMERIC NOT NULL,
    CONSTRAINT pk_calculation_request_sentence PRIMARY KEY (id)
);

COMMENT ON COLUMN calculation_request_sentence.id IS E'Description: The primary key of calculation_request_sentence \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence.calculation_request_id IS E'Description: The calculation request this sentence is associated with \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence.input_sentence_data_json IS E'Description: The definition of the sentence in JSON form \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence.sentence_adjustments_json IS E'Description: The definition of the adjustments associated with the sentence in JSON form \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence.impacts_final_release_date IS E'Description: Whether this sentence provided the final release date for the calculation \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence.release_multiplier IS E'Description: The multiplier used in calculating a release date for this sentence \nSource System: CRDS ';

CREATE INDEX idx_calculation_request_sentence_calculation_request_id ON calculation_request_sentence(calculation_request_id);

CREATE TABLE calculation_request_sentence_outcome
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_request_sentence_id   BIGINT NOT NULL REFERENCES calculation_request_sentence (id),
    calculation_date_type               VARCHAR(64) NOT NULL,
    outcome_date               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_calculation_request_sentence_outcome PRIMARY KEY (id)
);

COMMENT ON COLUMN calculation_request_sentence_outcome.id IS E'Description: The primary key of calculation_request_sentence_outcome \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence_outcome.calculation_request_sentence_id IS E'Description: The foreign key to calculation_request_sentence \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence_outcome.calculation_date_type IS E'Description: The type of the calculated date \nSource System: CRDS ';
COMMENT ON COLUMN calculation_request_sentence_outcome.outcome_date IS E'Description: The calculated date \nSource System: CRDS ';

CREATE INDEX idx_calculation_request_sentence_outcome_cr_sentence_id ON calculation_request_sentence_outcome(calculation_request_sentence_id);
CREATE INDEX idx_calculation_request_sentence_calculation_date_type ON calculation_request_sentence_outcome(calculation_date_type);
