CREATE TABLE operative_sentence_envelope
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calculation_request_id            BIGINT NOT NULL REFERENCES calculation_request (id),
    envelope_length_days              INTEGER NOT NULL,
    earliest_sentence_date            DATE NOT NULL,
    contains_sds_plus_sentence        BOOLEAN NOT NULL,
    is_post_recall                    BOOLEAN NOT NULL,
    CONSTRAINT pk_operative_sentence_envelope PRIMARY KEY (id)
);

COMMENT ON COLUMN operative_sentence_envelope.id IS E'Description: The primary key of operative_sentence_envelope \nSource System: CRDS ';
COMMENT ON COLUMN operative_sentence_envelope.calculation_request_id IS E'Description: The calculation request this is associated with \nSource System: CRDS ';
COMMENT ON COLUMN operative_sentence_envelope.envelope_length_days IS E'Description: The length in days of the operative sentence envelope \nSource System: CRDS ';
COMMENT ON COLUMN operative_sentence_envelope.earliest_sentence_date IS E'Description: The earliest sentence date in the envelope \nSource System: CRDS ';
COMMENT ON COLUMN operative_sentence_envelope.contains_sds_plus_sentence IS E'Description: Whether this sentence envelope contained any SDS plus sentences \nSource System: CRDS ';
COMMENT ON COLUMN operative_sentence_envelope.is_post_recall IS E'Description: Whether this sentence envelope is a post recall sentence envelope \nSource System: CRDS ';

CREATE INDEX idx_operative_sentence_envelope_calculation_request_id ON operative_sentence_envelope(calculation_request_id);
