name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "12 5 * * MON-FRI" # Every weekday at 05:12 UTC
jobs:
  security-veracode-pipeline-scan:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
